# Generated by Django 5.2.13 on 2026-05-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='province',
            field=models.CharField(blank=True, choices=[('Punjab', 'Punjab'), ('Sindh', 'Sindh'), ('KPK', 'Khyber Pakhtunkhwa'), ('Balochistan', 'Balochistan'), ('Islamabad', 'Islamabad Capital Territory'), ('Gilgit-Baltistan', 'Gilgit-Baltistan'), ('AJK', 'Azad Jammu & Kashmir')], max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='street_address',
            field=models.TextField(blank=True),
        ),
    ]
