# Generated by Django 5.2.13 on 2026-05-02 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material', models.CharField(choices=[('18k_gold', '18K Gold'), ('white_gold', 'White Gold'), ('platinum', 'Platinum'), ('silver', 'Sterling Silver'), ('mixed', 'Mixed metals')], default='18k_gold', max_length=32)),
                ('gemstone', models.CharField(blank=True, max_length=120)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
