# Generated by Django 5.2.13 on 2026-05-02 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_pakistan_marketplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, help_text='HTTPS image URL (shown when no file upload).', max_length=600)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/gallery/%Y/%m/')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='catalog.product')),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
    ]
